'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowUp, Plus, Minus, Component, CodeXml, Waypoints, MoveUpRight, FileDown, Mail, Phone } from 'lucide-react';
const projects = [
 {name:'Vidmagin',type:'HR TECH · WEBSITE REDESIGN',kind:'Professional work',image:'vidmagin.webp',title:'Complex product. Clear story.',desc:'A research-informed website redesign that connects product value, content hierarchy and a consistent visual language.',problem:'An HR-tech product needed a more focused website narrative and clearer information hierarchy.',approach:'Reviewed the existing content, reorganised the page story and designed responsive interfaces with a reusable visual system.',delivery:'Responsive design directions, structured developer handoff and 20+ supporting brand assets.',tags:['UX research','Responsive UI','Visual system']},
 {name:'ClientDesk',type:'SAAS · PRODUCT CONCEPT',kind:'Concept study',image:'clientdesk.webp',title:'Support, without the complexity.',desc:'Bringing a customer-support product into focus through a story built around the support lifecycle.',problem:'A broad support feature set can make it difficult to understand how a product fits into everyday work.',approach:'Organised the concept around the support lifecycle, with a clearer sequence from customer problem to product value.',delivery:'A SaaS website concept exploring content hierarchy, interface design and a cohesive product narrative.',tags:['SaaS design','Information architecture','Prototyping']},
 {name:'AakashAgro',type:'B2B EXPORT · WEB CONCEPT',kind:'Concept study',image:'aakash-agro.webp',title:'Local roots. Global ambition.',desc:'An export website concept shaped around product quality, origin and direct trade enquiries.',problem:'Trade buyers need to understand product quality and origin before taking the next step.',approach:'Built the landing-page story around origin, product quality, global proof and clear enquiry paths.',delivery:'A B2B website concept that balances an editorial brand story with practical buyer information.',tags:['Web design','B2B experience','Visual direction']}
];
export default function Home(){
 const [active,setActive]=useState<number|null>(null);const [copied,setCopied]=useState(false);
 useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));return()=>obs.disconnect()},[]);
 async function copy(){try{await navigator.clipboard.writeText('aakashprince2004@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{window.location.href='mailto:aakashprince2004@gmail.com'}}
 return <main id="top">
 <header className="nav"><a className="brand" href="#top" aria-label="Aakash home">Aakash P</a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a></nav><a className="nav-contact" href="#contact">Let’s talk <ArrowUpRight size={17}/></a></header>
 <section className="hero wrap">
 <div className="hero-intro"><img src="./profile/aakash-hero.jpeg" width="48" height="48" fetchPriority="high" decoding="async" alt="Aakash P"/><span>Hi, I’m Aakash — UI/UX & Product Designer</span></div>
 <h1><span className="line-mask"><span className="line-text">Thoughtful design.</span></span><span className="line-mask hero-muted"><span className="line-text">Made for people.</span></span></h1>
 <p className="hero-description">I shape complex ideas into clear digital experiences.<br className="desktop-break"/> From the first Figma frame to a website you can use.</p>
 <div className="hero-actions"><a className="button-primary" href="#work">Explore my work <ArrowDown size={18}/></a><a className="button-secondary" href="./resume/Aakash_P_Resume.pdf" target="_blank" rel="noreferrer">View résumé <FileDown size={18}/></a></div>
 <div className="hero-note"><span>Based in Coimbatore, India</span><span>Open to freelance projects</span></div>
 </section>
 <section id="work" className="work wrap"><div className="section-heading reveal"><div><span className="eyebrow">01 / SELECTED WORK</span><h2>A selection of<br/><em>thoughtful work.</em></h2></div><p>Websites and product concepts.<br/>Each with a different problem to solve.</p></div><div className="projects">{projects.map((p,i)=><article className="project reveal" key={p.name}><button className={'project-visual project-'+i} onClick={()=>setActive(active===i?null:i)} aria-expanded={active===i} aria-controls={'detail-'+i}><div className="project-overline"><span>{p.kind}</span><span>0{i+1} / 03</span></div><img width={i===2?1707:2400} height={i===0?812:i===1?1600:960} src={'./project-covers/'+p.image} alt={p.name+' website design preview'} loading="lazy"/><span className="project-open">{active===i?'Close project':'Explore project'} {active===i?<Minus size={19}/>:<ArrowUpRight size={19}/>}</span></button><div className="project-info"><div><span className="eyebrow">{p.type}</span><h3>{p.name}</h3></div><p>{p.desc}</p><button className="round-button" onClick={()=>setActive(active===i?null:i)} aria-label={(active===i?'Close ':'Read ')+p.name+' project'} aria-expanded={active===i}>{active===i?<Minus/>:<Plus/>}</button></div><div id={'detail-'+i} className={'project-details '+(active===i?'expanded':'')} hidden={active!==i}><h4>{p.title}</h4><div className="detail-grid">{[['The challenge',p.problem],['My approach',p.approach],['What I delivered',p.delivery]].map(([a,b])=><div key={a}><span className="eyebrow">{a}</span><p>{b}</p></div>)}</div><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
 <section id="about" className="about"><div className="wrap about-grid"><div className="portrait reveal"><img src="./profile/aakash-about.jpeg" alt="Aakash P, UI/UX and product designer" loading="lazy"/><span className="portrait-caption">AAKASH P · DESIGNER & CURIOUS HUMAN</span></div><div className="about-copy reveal"><span className="eyebrow">02 / A LITTLE ABOUT ME</span><h2>A designer who cares<br/>about <em>the details.</em></h2><p>I’m Aakash, a designer based in Coimbatore. I enjoy untangling complex workflows and turning them into interfaces people can use with confidence.</p><p>At Jeevan Infotech, I design business software, working closely with developers to connect thoughtful design with real-world constraints.</p><p>Figma is central to my work: components, auto layout, prototypes and design systems. I also build websites through AI-assisted front-end development. For freelance projects, I can help with product interfaces, website design and responsive implementation.</p><a className="text-link" href="./resume/Aakash_P_Resume.pdf" target="_blank" rel="noreferrer">View my résumé <FileDown size={19}/></a></div><div className="stats reveal"><div><strong>07</strong><span>Portfolio projects</span></div><div><strong>03</strong><span>Professional experiences</span></div><div><strong>20+</strong><span>Brand assets at Vidmagin</span></div></div></div></section>
 <section className="capabilities wrap"><div className="section-heading reveal"><div><span className="eyebrow">03 / MY TOOLKIT</span><h2>Design, from the<br/><em>inside out.</em></h2></div><p>Design is the foundation.<br/>Curiosity takes it further.</p></div><div className="skills-grid">{[{icon:<Component/>,n:'01',t:'Figma & design systems',d:'Reusable components, thoughtful variants, auto layout and prototypes that communicate how a product should feel.',tags:'DESIGN SYSTEMS / PROTOTYPING'},{icon:<Waypoints/>,n:'02',t:'Product & UX design',d:'Research, user flows and information architecture that turn complex forms and data-heavy workflows into understandable steps.',tags:'UX THINKING / PRODUCT DESIGN'},{icon:<CodeXml/>,n:'03',t:'Design to development',d:'Working websites built from design intent. I use AI-assisted development alongside HTML, CSS and JavaScript fundamentals to refine layouts, interactions and responsive behaviour.',tags:'AI-ASSISTED BUILD / HTML & CSS'}].map(s=><article className="skill reveal" key={s.n}><div>{s.icon}<span>{s.n}</span></div><h3>{s.t}</h3><p>{s.d}</p><span className="skill-tags">{s.tags}</span></article>)}</div></section>
 <section id="experience" className="experience wrap"><div className="experience-title reveal"><span className="eyebrow">04 / THE JOURNEY</span><h2>A little more<br/><em>experience.</em></h2><a className="text-link" href="./resume/Aakash_P_Resume.pdf" target="_blank" rel="noreferrer">View résumé <FileDown size={18}/></a></div><div className="timeline">{[{date:'PRESENT',name:'Jeevan Infotech',role:'Junior Designer',desc:'Designing responsive business software, reusable components and implementation-ready interaction patterns.'},{date:'DEC 2025 — FEB 2026',name:'Vidmagin Innovations',role:'UI/UX Designer',desc:'UX research, website redesign and developer handoff. Created 20+ presentation, poster and social assets.'},{date:'JUL 2025 — NOV 2025',name:'E-Sutra Technologies',role:'UI/UX Designer Intern',desc:'Responsive web and mobile interfaces across 3+ client projects, from user flows to interactive Figma prototypes.'}].map((e,i)=><article className="reveal" key={e.name}><div className="job-date">{e.date}{i===0&&<span className="current">CURRENT</span>}</div><h3>{e.name}</h3><span className="job-role">{e.role}</span><p>{e.desc}</p></article>)}<div className="education reveal"><span className="eyebrow">BUILT ON A SOLID FOUNDATION</span><p>BCA · KG College of Arts and Science</p><p>UI/UX Professional Course · FITA Academy</p></div></div></section>
 <footer id="contact"><div className="wrap reveal"><div className="contact-top"><span className="eyebrow">OPEN FOR FREELANCE DESIGN & WEBSITE PROJECTS</span><span>COIMBATORE, INDIA</span></div><a className="contact-title" href="mailto:aakashprince2004@gmail.com">Let’s talk.<MoveUpRight/></a><div className="contact-details"><div><a className="email" href="mailto:aakashprince2004@gmail.com">aakashprince2004@gmail.com</a><button className="copy" onClick={copy}>{copied?'Copied!':'Copy email'}</button><span role="status" className="sr-only">{copied?'Email copied to clipboard':''}</span></div><div className="socials"><a href="https://www.linkedin.com/in/designeraakash01" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={17}/></a><a href="mailto:aakashprince2004@gmail.com">Email <Mail size={17}/></a><a href="tel:+916381659522">Call me <Phone size={16}/></a></div></div><div className="footer-bottom"><span>© 2026 AAKASH P</span><span>THOUGHTFULLY DESIGNED. ALWAYS EVOLVING.</span><a href="#top">BACK TO TOP <ArrowUp size={15}/></a></div></div></footer>
 </main>
}
